# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "eee22281931f519bdb464264364a655c"
name = "backend-test-app"
handle = "backend-test-app-3"
application_url = "https://placement-computing-maybe-fail.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://placement-computing-maybe-fail.trycloudflare.com/auth/callback", "https://placement-computing-maybe-fail.trycloudflare.com/auth/shopify/callback", "https://placement-computing-maybe-fail.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
